### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by Jirubizu** [Rishu20/Blackarchwsl#1]
When I try to do `sudo pacman -Syu` I get the following issue.

```
:: Synchronizing package databases...
error: failed retrieving file 'core.db' from ind.mirror.pkgbuild.com : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'core.db' from mirrors.piconets.webwerks.in : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'core.db' from mirror.cse.iitk.ac.in : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'core.db' from mirrors.piconets.webwerks.in : Resolving timed out after 10000 milliseconds
error: failed to update core (download library error)
error: failed retrieving file 'extra.db' from ind.mirror.pkgbuild.com : Could not resolve host: ind.mirror.pkgbuild.com
error: failed retrieving file 'extra.db' from mirrors.piconets.webwerks.in : SSL certificate problem: certificate has expired
 extra                                      1646.9 KiB   465 KiB/s 00:04 [########################################] 100%
error: failed retrieving file 'community.db' from ind.mirror.pkgbuild.com : Resolving timed out after 10000 milliseconds
 community                                     5.3 MiB  3.38 MiB/s 00:02 [########################################] 100%
error: failed retrieving file 'blackarch.db' from www.mirrorservice.org : Resolving timed out after 10000 milliseconds
error: failed to update blackarch (download library error)
error: failed to synchronize all databases
```

but once I change my DNS to 8.8.8.8 I get the following output, majority of its downloads but it's still failing to resolve and I am unsure of why and then fails on pgp

https://hastebin.com/uxajerumik.coffeescript

**Comment by djsunn** [comment]
Correct your /etc/resolv.conf
This one is empty after initial setup.

**Comment by Rishu20** [comment]
Thanks for the intel i will work on it

**Comment by Rishu20** [comment]
> When I try to do `sudo pacman -Syu` I get the following issue.
> 
> ```
> :: Synchronizing package databases...
> error: failed retrieving file 'core.db' from ind.mirror.pkgbuild.com : Resolving timed out after 10000 milliseconds
> error: failed retrieving file 'core.db' from mirrors.piconets.webwerks.in : Resolving timed out after 10000 milliseconds
> error: failed retrieving file 'core.db' from mirror.cse.iitk.ac.in : Resolving timed out after 10000 milliseconds
> error: failed retrieving file 'core.db' from mirrors.piconets.webwerks.in : Resolving timed out after 10000 milliseconds
> error: failed to update core (download library error)
> error: failed retrieving file 'extra.db' from ind.mirror.pkgbuild.com : Could not resolve host: ind.mirror.pkgbuild.com
> error: failed retrieving file 'extra.db' from mirrors.piconets.webwerks.in : SSL certificate problem: certificate has expired
>  extra                                      1646.9 KiB   465 KiB/s 00:04 [########################################] 100%
> error: failed retrieving file 'community.db' from ind.mirror.pkgbuild.com : Resolving timed out after 10000 milliseconds
>  community                                     5.3 MiB  3.38 MiB/s 00:02 [########################################] 100%
> error: failed retrieving file 'blackarch.db' from www.mirrorservice.org : Resolving timed out after 10000 milliseconds
> error: failed to update blackarch (download library error)
> error: failed to synchronize all databases
> ```
> 
> but once I change my DNS to 8.8.8.8 I get the following output, majority of its downloads but it's still failing to resolve and I am unsure of why and then fails on pgp
> 
> https://hastebin.com/uxajerumik.coffeescript
try to update the /etc/pacman.d/mirrorlist file

**Comment by geniuskidkanyi** [comment]
to fix this error create a file in ```/etc/resolv.conf``` and add following 
```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 192.168.192.1
```

**Comment by Rishu20** [comment]
reset the locale all the issue is all about
